title: Takaaki Yoshikawa # your name (or website title) here
logo: "/images/taka.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A data lover doing something with data for ca. 365 days a year
  <br><br>
  Aslo a long distance runner running 10k or so for ca. 200 days a year 
  <br><br>
  <a href="https://www.linkedin.com/in/takaakiyoshikawa/">LinkedIn</a>

theme: jekyll-theme-minimal
google_analytics: G-XNDM0KR9EC # your Google Analytics tracking ID here
